INSERT INTO phones (number, user_id)
VALUES ('123-456-7890', 1), -- Admin
       ('333-333-3333', 5), -- Admin
       ('444-444-4444', 6), -- Admin
       ('555-555-5555', 11); -- Admin


INSERT INTO posts (title, content, user_id)
VALUES ('Best Board Games of 2024', 'Let\'s discuss the best board games of 2024...', 1),
       ('Tips for New Players', 'Here are some tips for new board game players...', 2),
       ('Board Game Recommendations', 'Can anyone recommend some good board games?', 3),
       ('Favorite Strategy Games', 'What are your favorite strategy board games?', 4),
       ('Best Cooperative Games', 'Share your favorite cooperative board games!', 5),
       ('Top Card Games', 'What are the top card games this year?', 6),
       ('Family Game Night Ideas', 'Ideas for a fun family game night.', 7),
       ('Solo Board Games', 'Good board games to play solo.', 8),
       ('Game Reviews', 'Post your board game reviews here.', 9),
       ('Upcoming Game Releases', 'Discuss upcoming board game releases.', 10),
       ('Classic Board Games', 'Which classic board games do you love?', 11),
       ('Best Party Games', 'Best board games for parties.', 12),
       ('Educational Games', 'Board games that are educational.', 13),
       ('Most Challenging Games', 'What are the most challenging board games?', 14),
       ('Quick Play Games', 'Games that are quick to play.', 15),
       ('Best Game Components', 'Games with the best components.', 16),
       ('Unique Game Mechanics', 'Discuss unique game mechanics.', 17),
       ('Game Strategies', 'Share your game strategies here.', 18),
       ('Games for Large Groups', 'Best games for large groups.', 19),
       ('Games for Kids', 'Board games suitable for kids.', 20),
       ('The Best Board Games for Beginners',
        'I think these board games are great for beginners: Catan, Ticket to Ride, and Carcassonne. What do you think?',
        1),
       ('Advanced Strategies for Chess',
        'Let’s discuss some advanced strategies that have helped you win more games in chess.', 2),
       ('Best Two-Player Games', 'What are your favorite two-player games? I love Jaipur and Lost Cities.', 3),
       ('Favorite Cooperative Board Games', 'Which cooperative board games do you enjoy playing with your friends?', 4),
       ('Top 10 Party Games', 'Let’s share our top 10 favorite party games for large groups!', 5),
       ('Eurogames vs. Ameritrash: Which Do You Prefer?', 'Which type of board game do you prefer and why?', 6),
       ('Best Solo Board Games', 'Any recommendations for solo board games?', 7),
       ('The Evolution of Board Game Design', 'How do you think board game design has evolved over the years?', 8),
       ('Kickstarter Board Games Worth Backing', 'Have you backed any good board games on Kickstarter recently?', 9),
       ('Deck-Building Games Recommendations',
        'I’m looking for some deck-building games to add to my collection. Any recommendations?', 10),
       ('Most Underrated Board Games', 'What are some underrated board games that deserve more attention?', 11),
       ('Best Thematic Board Games', 'Which board games have the best themes in your opinion?', 12),
       ('Strategies for Catan', 'What strategies do you use to win in Catan?', 13),
       ('How to Teach Board Games to New Players',
        'What’s the best way to introduce board games to people who are new to the hobby?', 14),
       ('Board Games for Kids', 'What are the best board games for kids under 10?', 15),
       ('Board Games for Family Gatherings',
        'Looking for recommendations for board games that are great for family gatherings.', 16),
       ('Expansions That Are Worth It', 'Which board game expansions do you think are worth purchasing?', 17),
       ('Games with the Best Artwork', 'What board games do you think have the best artwork?', 18),
       ('Your Favorite Board Game Mechanics', 'Let’s discuss our favorite board game mechanics and why we like them.',
        19),
       ('Best Game for New Gamers', 'What game would you recommend to someone who’s just getting into board games?',
        20),
       ('Biggest Board Game Disappointments', 'What board games did not live up to your expectations?', 1),
       ('Board Games with the Best Components', 'Which board games have the best quality components?', 2),
       ('Card Games Worth Playing', 'What card games do you enjoy playing?', 3),
       ('Worker Placement Games', 'Let’s talk about our favorite worker placement games.', 4),
       ('Games to Play with Non-Gamers', 'What board games do you recommend for people who don’t typically play games?',
        5),
       ('How to Store Your Board Games', 'Any tips on how to organize and store a large board game collection?', 6),
       ('The Impact of Digital Board Games', 'How do you think digital adaptations of board games impact the hobby?',
        7),
       ('Board Game Conventions', 'Have you attended any board game conventions? What was your experience like?', 8),
       ('Best Games with Miniatures', 'Which board games have the coolest miniatures?', 9),
       ('Your Most Played Board Game', 'Which board game do you play the most and why?', 10);


INSERT INTO comments (content, user_id, post_id)
VALUES ('I think Gloomhaven is the best!', 3, 1),
       ('Thanks for the tips!', 4, 2),
       ('I recommend Catan and Carcassonne.', 2, 3),
       ('I love Twilight Struggle.', 1, 4),
       ('Pandemic is a great cooperative game.', 5, 5),
       ('I enjoy playing Dominion.', 6, 6),
       ('We love Ticket to Ride for family night.', 7, 7),
       ('Friday is a great solo game.', 8, 8),
       ('Here is my review of Wingspan.', 9, 9),
       ('Looking forward to the new expansion.', 10, 10),
       ('Chess is a classic favorite.', 11, 11),
       ('Codenames is perfect for parties.', 12, 12),
       ('We use board games in our classroom.', 13, 13),
       ('Mage Knight is very challenging.', 14, 14),
       ('Love games that are quick and fun.', 15, 15),
       ('Scythe has amazing components.', 16, 16),
       ('Azul has unique mechanics.', 17, 17),
       ('Here are some strategies for Risk.', 18, 18),
       ('Werewolf is great for large groups.', 19, 19),
       ('My kids love playing Candy Land.', 20, 20),
       ('Catan is definitely a classic! I also recommend Splendor.', 2, 1),
       ('Endgame strategies are crucial in chess.', 3, 2),
       ('I second Jaipur! Also, check out Patchwork.', 4, 3),
       ('Pandemic is my go-to cooperative game.', 5, 4),
       ('For large groups, I love Codenames and Werewolf.', 6, 5),
       ('I prefer Eurogames because of their deep strategy.', 7, 6),
       ('Terraforming Mars is great solo!', 8, 7),
       ('Design has become much more player-centric over the years.', 9, 8),
       ('I recently backed Frosthaven, can’t wait for it to arrive.', 10, 9),
       ('Dominion and Star Realms are excellent deck-builders.', 11, 10),
       ('Concordia is so underrated, it’s a hidden gem.', 12, 11),
       ('Mansions of Madness has an incredible theme!', 13, 12),
       ('Focus on longest road early on.', 14, 13),
       ('Start with something simple like Codenames.', 15, 14),
       ('My kids love Ticket to Ride: First Journey.', 16, 15),
       ('Try Telestrations, always a hit with the family.', 17, 16),
       ('The Carcassonne expansions really add to the game.', 18, 17),
       ('Scythe has some of the best artwork I’ve seen.', 19, 18),
       ('I love deck-building combined with worker placement.', 20, 19),
       ('Definitely Ticket to Ride for new gamers.', 1, 20),
       ('Gloomhaven was a big letdown for me.', 2, 21),
       ('Everdell’s components are top-notch!', 3, 22),
       ('I always enjoy playing The Mind with friends.', 4, 23),
       ('Viticulture is a solid worker placement game.', 5, 24),
       ('Sushi Go is great for non-gamers.', 6, 25),
       ('I use Kallax shelves for storing my games.', 7, 26),
       ('Digital games are great, but they can never replace the physical experience.', 8, 27),
       ('Gen Con was amazing! So many games to try out.', 9, 28),
       ('Rising Sun has some of the best miniatures I’ve seen.', 10, 29),
       ('I play Azul almost every weekend.', 11, 30);


INSERT INTO tags (name)
VALUES ('Strategy'),
       ('Family'),
       ('Card Game'),
       ('Cooperative'),
       ('Solo'),
       ('Party'),
       ('Educational'),
       ('Classic'),
       ('Challenging'),
       ('Quick Play');


INSERT INTO posts_tags (post_id, tag_id)
VALUES (1, 1),
       (1, 4),
       (2, 2),
       (3, 1),
       (3, 2),
       (4, 1),
       (5, 4),
       (6, 3),
       (7, 2),
       (8, 5),
       (9, 1),
       (10, 1),
       (11, 8),
       (12, 6),
       (13, 7),
       (14, 9),
       (15, 10),
       (16, 1),
       (17, 1),
       (18, 1),
       (19, 2),
       (20, 2);


INSERT INTO reactions (post_id, user_id, reaction_type)
VALUES (1, 2, 'LIKE'),
       (1, 3, 'LIKE'),
       (2, 1, 'DISLIKE'),
       (2, 4, 'LIKE'),
       (3, 1, 'LIKE'),
       (4, 2, 'DISLIKE'),
       (5, 3, 'LIKE'),
       (6, 4, 'LIKE'),
       (7, 5, 'LIKE'),
       (8, 6, 'DISLIKE'),
       (9, 7, 'LIKE'),
       (10, 8, 'LIKE'),
       (11, 9, 'DISLIKE'),
       (12, 10, 'LIKE'),
       (13, 11, 'LIKE'),
       (14, 12, 'DISLIKE'),
       (15, 13, 'LIKE'),
       (16, 14, 'LIKE'),
       (17, 15, 'DISLIKE'),
       (18, 16, 'LIKE'),
       (19, 17, 'LIKE'),
       (20, 18, 'DISLIKE');